version: "3.9"
services:
  web:
    build: .
    ports:
      - "5050:5050"
    command: python manage.py runserver 0.0.0.0:5050
    volumes:
      - .:/code
    env_file:
      - .env
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
