# Generated by Django 4.2.3 on 2023-07-31 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('insta_app', '0004_alter_image_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='likers',
            field=models.ManyToManyField(related_name='liked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
