# Generated by Django 4.2.3 on 2023-08-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insta_app", "0006_comment_created_at_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="image/"),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile/"),
        ),
    ]
